### ISSUE TITLE
Missing or incomplete headers

### ISSUE THREAD

**Issue by Erwane** [master131/msg2eml.js#6]
Hi,

When i convert MSG to EML, some headers are missing or incomplete : 

```
Received: from [192.168.23.10] (xxx)	by
   xxx (xxx ESMTP) with ESMTPSA id EBFF31764496	for
   <xxx>; Mon, 12 Dec 2022 09:59:49 +0100 (CET)
``` 
is only converted to

```
Received: from [xxx] (xxx [xxx])
```
And multiple received headers was removed, only last is kept.

Could you try to fix this please ? 
Headers can me multiple and on multiple lines to (line start by a space)

Attached the msg, converted eml and convert by aconvert website.

Thanks a lot.

[Test-message.zip](https://github.com/master131/msg2eml.js/files/10206517/Test-message.zip)

**Comment by Erwane** [comment]
The inline attachements and normal attachements are missing too :(

**Comment by master131** [comment]
Hi @Erwane, I've just pushed an update which preserves the original headers from the MSG file - can you see if it's better now?

**Comment by Erwane** [comment]
really much better. Thanks.

About inline and attached files, could you maybe find a way to fix it too ?
I can send you a msg example in private if you need.

Thanks a lot.

**Comment by master131** [comment]
As in preserving the headers from the original attachments? Or is there some rendering issue with inline attachments - if I can have a sample that would be good.

**Comment by Erwane** [comment]
How can i send you sample ? there is RGPD data in my emails examples.
Thanks.

**Comment by master131** [comment]
Shoot me a DM on Twitter:
master131_

**Comment by master131** [comment]
Hey, didn't get a response regarding the changes via DM, but have pushed them to Github anyway for you to check when you're able to.

**Comment by Erwane** [comment]
Sorry, i couldn't answer this week-end.
Thanks for your work, it's really wonderful.

~~The second attachment is missing but maybe because it is a gpg signature ?~~
~~Does this will append with two normal attachments ?~~
edit: the gpg signature is present and well detected by thunderbird

Thunderbird add an extra message about displaying external image on the "inline" attachment.
If you can encode the `.` in the `cid:` url, i'm pretty sure it will be good.
`cid:part1.RrZf0Ozc.Y900quUQ@domain.com` to `cid:part1=2ERrZf0Ozc=2EY900quUQ@domain=2Ecom` 

Thanks again for your work.

**Comment by master131** [comment]
I'm not seeing that message on Thunderbird, at least on Windows, the signature in the email renders inline without issue for me and the `cid:part1.RrZf0Ozc.Y900quUQ@oktey.com` portion is correctly encoded using quoted-printable (this is how it is in the original message, completely untouched).

The EML you provided (eml-created-by-outlook.eml) that was produced by Microsoft Outlook also has the CID encoded the same way, untouched.

**Comment by Erwane** [comment]
Ok, you're right. Conversion is really nice now.
I will make some try and send you feedback after more tests.
thanks.
